### ISSUE TITLE
"Change configurations"

### ISSUE THREAD

**Issue by palmerlevey** [atduarte/sms-cli#1]
In the readme, you should clarify what `count: 5,` is for in the configuration. As well, it should specifically state that the `device: null` parameter requires the Device ID numeric ID. 

Also, there is no guide/step that states `npm install` is required within the repo structure. 

As well, what are the parameters or options of the tool? Does it only check for messages, or is there an ability to 'sendMessage'?

**Comment by atduarte** [comment]
Count represents the number of messages that will show up when running. Will change both field names and add some documentation. 

Ups, missed npm install.

It shows the last messages (received or sent) and allows to answer to those or to a specific number. Will add some screenshots and user documentation info, later today.

Thanks!

**Comment by palmerlevey** [comment]
Thanks @atduarte
